SDIT-1703 Create a parallel executor per package (#625)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,6 +10,12 @@ parameters:
   releases-slack-channel:
     type: string
     default: dps-releases
+  test-executor-packages:
+    type: string
+    default: "activities adjudications alerts appointments courtsentencing csip incidents locations sentencing visits"
+  test-executors-count:
+    type: integer
+    default: 11
 
 jobs:
   validate:
@@ -30,7 +36,7 @@ jobs:
           key: gradle-{{ checksum "build.gradle.kts" }}
 
   tests:
-    parallelism: 4
+    parallelism: << pipeline.parameters.test-executors-count >>
     executor:
       name: hmpps/java_localstack_postgres
       jdk_tag: "21.0"
@@ -49,22 +55,75 @@ jobs:
           command: |
             cd src/test/kotlin
             
-            # Find all Kotlin files that contain tests, write the filenames to filenames.txt and tell CircleCI to split them by filesize across the parallel executors
-            circleci tests glob "**/*.kt" \
-            | xargs grep -l -E '@Test|@ParameterizedTest' \
-            | cut -c 1- \
-            | circleci tests run --command=">filenames.txt xargs echo" \
-            --verbose \
-            --split-by=filesize
+            # Find all packages            
+            all_packages=($(find uk/gov/justice/digital/hmpps/prisonerfromnomismigration -mindepth 1 -maxdepth 1 -type d -exec basename {} \;))
+
+            # Get all packages that require a dedicated executor
+            dedicated_executor_packages=()
+            for i in << pipeline.parameters.test-executor-packages >>; do dedicated_executor_packages+=($i); done
+
+            # Validate parameter test-executors-count (which needs to be a parameter because it's used in the "parallelism" declaration)
+            required_executors="${#dedicated_executor_packages[@]}"
+            if [[ $CIRCLE_NODE_TOTAL -ne $((required_executors+1)) ]]; then
+              echo "The 'test-executors-count' must be 1 more than the number of packages in parameter 'test-executor-packages".
+              exit 1
+            fi
             
-            # Fail the build if no test files were found
-            [ -s filenames.txt ] || circleci-agent step halt
+            # Get all other packages that don't require a dedicated executor - these will be run on a single executor
+            common_executor_packages=()
+            for package in "${all_packages[@]}"; do
+              if [[ ! " ${dedicated_executor_packages[@]} " =~ " ${package} " ]]; then
+                common_executor_packages+=("$package")
+              fi
+            done
+
+            # Function to find test classes for a package and write them to file
+            find_test_classes() {
+              local package=$1
+              local output_file=$2
+            
+              if [ -d "uk/gov/justice/digital/hmpps/prisonerfromnomismigration/$package" ]; then
+                local test_files=$(find "uk/gov/justice/digital/hmpps/prisonerfromnomismigration/$package" -name "*.kt" \
+                  | xargs -r grep -l -E '@Test|@ParameterizedTest' 2>/dev/null || true)
+                echo "Found test_files for package=$package: $test_files"
+                
+                # Convert test files to class names
+                if [ ! -z "$test_files" ]; then
+                  echo "$test_files" \
+                    | sed 's@/@.@g' \
+                    | sed 's/\.kt//g' \
+                    >> "$output_file"
+                fi
+              else
+                echo "Directory uk/gov/justice/digital/hmpps/prisonerfromnomismigration/$package does not exist. Check parameter test-executor-packages."
+                exit 1
+              fi
+            }
+            
+            index_output_file="test_classes$CIRCLE_NODE_INDEX.txt"
+            > "$index_output_file"
+            
+            if [[ "$CIRCLE_NODE_INDEX" -lt "$((CIRCLE_NODE_TOTAL-1))" ]]; then
+              # Create a file containing the classes for this dedicated executor package
+              echo "Finding test classes for dedicated executor from package=${dedicated_executor_packages[$CIRCLE_NODE_INDEX]}"
+              find_test_classes "${dedicated_executor_packages[$CIRCLE_NODE_INDEX]}" "$index_output_file"
+            else
+              # Create a single file to contain test classes bundled from all other packages
+              echo "Finding test classes for common executor from packages=${common_executor_packages[@]}"
+              for common_executor_package in "${common_executor_packages[@]}"; do
+                find_test_classes "$common_executor_package" "$index_output_file"
+              done
+            fi
+            
+            echo "Executor $CIRCLE_NODE_INDEX will run tests for classes: $(cat $index_output_file)"
+
+            # Fail the build if no test files were found - unless we're in the bundled executor (which could potentially have zero tests)
+            if [[ "$CIRCLE_NODE_INDEX" -lt "$((CIRCLE_NODE_TOTAL-1))" ]]; then
+              [ -s test_classes$CIRCLE_NODE_INDEX.txt ] || circleci-agent step halt
+            fi
       - run:
           command: |
-            # Convert filenames for this parallel executor into packages/classes for Gradle test arguments
-            GRADLE_ARGS=$(cat src/test/kotlin/filenames.txt \
-            | sed 's@/@.@g' \
-            | sed 's/\.kt//g' \
+            GRADLE_ARGS=$(cat src/test/kotlin/test_classes$CIRCLE_NODE_INDEX.txt \
             | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
             
             echo "Prepared arguments for Gradle: $GRADLE_ARGS"
